title: Paleo Data Knowledge Hub
description: A clearinghouse for information about data related to paleontology specimens and collections
repository: paleo-data/paleo-data.github.io
url: https://paleo-data.github.io
baseurl: knowledge-hub
theme: minimal-mistakes-jekyll
logo: /assets/images/trilocorn.png
logo_alt: A trilobite with a unicorn horn and ears
og_image: /assets/images/trilocorn.png
exclude: [scripts, templates]
footer:
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/orgs/paleo-data"
    - label: "Slack"
      icon: "fa-brands fa-slack"
      url: "https://paleo-data.slack.com/"
    - label: "Listserv"
      icon: "fa-solid fa-envelope"
      url: "https://groups.google.com/g/paleo-data/about"
    - label: "Community Norms"
      icon: "fa-solid fa-people-group"
      url: "https://paleo-data.github.io/community/norms"
      
atom_feed:
  hide: true

after_footer_scripts:
  - /assets/js/custom.js

search: true
search_full_content: true
lunr:
  search_within_pages: true

collections_dir: collections
collections:
  community:
    output: True
    sort_by: nav_order
  "highlighted-resources":
    output: True
    sort_by: nav_order
  explanations:
    output: True
    sort_by: nav_order
  "how-to-guides":
    output: True
    sort_by: nav_order
  tutorials:
    output: True
    sort_by: nav_order

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: sidebar
        collapsible: True
  - scope:
      path: collections
    values:
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: community
    values:
      section: Community
      sidebar:
        expanded: [community]
  - scope:
      path: ""
      type: explanations
    values:
      section: Explanations
      sidebar:
        expanded: [explanations]
  - scope:
      path: ""
      type: how-to-guides
    values:
      section: How To Guides
      sidebar:
        expanded: [how-to-guides]
  - scope:
      path: ""
      type: highlighted-resources
    values:
      section: Highlighted Resources
      sidebar:
        expanded: [highlighted-resources]
  - scope:
      path: ""
      type: tutorials
    values:
      section: Tutorials
      sidebar:
        expanded: [tutorials]
